name: deploy

on:
  push:
    paths-ignore:
    - 'docs/**'
    branches:
    - main
  schedule:
    - cron: '10 9 * * 1'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/configure-pages@v5
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm
    - run: |
        mkdir -p ~/.local/bin
        curl -L $WASM_PACK_URL | tar -zxf -
        cp ./wasm-pack-*/wasm-pack ~/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      env:
        WASM_PACK_URL: 'https://github.com/rustwasm/wasm-pack/releases/download/v0.13.1/wasm-pack-v0.13.1-x86_64-unknown-linux-musl.tar.gz'
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs
    - id: deployment
      uses: actions/deploy-pages@v4

# vim: set ts=2 sts=2 sw=2:
