name: deploy

on: push
#on:
#  push:
#    branches:
#    - master
#    paths:
#    - 'Cargo.*'
#    - 'src/**'
#    - 'www/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        mkdir ~/.npm
        npm config set prefix ~/.npm
        cargo install wasm-pack
        wasm-pack build
        (cd pkg && npm link)
        rm -f docs/*.wasm
        (cd www && npm install && npm link seqdia && npm run build -- --mode=production)
    - run: |
        echo "$SSH_KEY" > ~/.ssh/id_ed25519
        git remote show origin
        git remote set origin 'git@github.com:yskszk63/seqdia.git'
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m'deploy ghpages'
        git push
      env:
        SSH_KEY: ${{ secrets. GH_SSH_KEY }}

# vim: set ts=2 sts=2 sw=2:
