name: deploy

on: push
#on:
#  push:
#    branches:
#    - master
#    paths:
#    - 'Cargo.*'
#    - 'src/**'
#    - 'www/***'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        mkdir ~/.npm
        npm config set prefix ~/.npm
        cargo install wasm-pack
        wasm-pack build
        (cd pkg && npm link)
        (cd www && npm install && npm link seqdia && npm build)
    - run: |
        git status
        git add .
        git commit -m'deploy ghpages'
        git push

# vim: set ts=2 sts=2 sw=2:
