name: deploy

on: push
#on:
#  push:
#    branches:
#    - master
#    paths:
#    - 'Cargo.*'
#    - 'src/**'
#    - 'www/***'

jobs:
  build:
    runs-on: ubunts-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        cargo install wasm-pack
        wasm-pack build

# vim: set ts=2 sts=2 sw=2:
