name: deploy

on:
  push:
    branches:
    - master
    paths:
    - 'Cargo.*'
    - 'src/**'
    - 'www/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        mkdir ~/.npm
        npm config set prefix ~/.npm
        cargo install wasm-pack
        wasm-pack build
        (cd pkg && npm link)
        rm -f docs/*.wasm
        (cd www && npm install && npm link seqdia && npm run build -- --mode=production)
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs
        git commit -m'deploy ghpages'
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

# vim: set ts=2 sts=2 sw=2:
